export const IMAGES = {
  hero: "/assets/images/upscaleimage.jpeg",
  about: "/assets/images/principal.jpeg",
  signature: "https://lh3.googleusercontent.com/aida-public/AB6AXuA1upKRIVwYLIGBtIAARAVaZWaqbfGF-T3TMCMGgZFarfRRN04pYmFy5hY9hHOJ1BN0sTYcLDkkVF9PLHXRwISVRDQyw9YQNFcvGR0jNv3Xs_mgJsNirIguMB8cmledPVhO-iW-wmT0A8K2WN5XR2G3XSakL790E7_goo3NCA8kjuRw1NzDw7e0QhdnLveQ_pvhPrGgzUiMIMoQr_H7Z9wvTNodt_Up-8ijbSE3VD9lphujmrKFfjq3QJUobRhjzJujLnaB1MDdpmjb",
  service1: "/assets/images/service_atendimento.png",
  service2: "/assets/images/service_mentoria_ind.png",
  service3: "/assets/images/service_mentoria_bellas.png",
  service4: "/assets/images/service_portal.png",
  service5: "/assets/images/service_curso.png",
  btn1: "/assets/images/1.jpeg",
  btn2: "/assets/images/2.jpeg",
  btn3: "/assets/images/3.jpeg",
  btn4: "/assets/images/4.jpeg",
  btn5: "/assets/images/5.jpeg",
  btn6: "/assets/images/6.jpeg",
  portalVideo: "/assets/images/portal_video.mp4",
};